env:
  'https://bvt.xm-test.bestcem.com'
log_level:
  INFO
admin_user:
  org_code: 'bvt'
  user_name: 'superadmin'
  password: '1234567890'
sub_user:
  org_code: 'bvt'
  user_name: 'test01'
  password: '1234567890'
email:
  flag: 'true'
  stmp_address: 'zongxiuxuan001@163.com'
  stmp_password: 'zxx190825'
  stmp_server: 'smtp.163.com'
  stmp_port: '25'
  send_to: ['zongxiuxuan001@163.com']